[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin-latte.toml"
]
[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Medium"}
size = 10.5
[keyboard]
bindings = [
    { key = "\\", mods = "Control | Shift", action = "ReceiveChar" }
]
[window]
opacity = 0.55
